package com.example.dpi.report;

import com.fasterxml.jackson.databind.ObjectMapper;


import java.io.File;
import java.io.IOException;
import java.io.FileWriter;
import java.util.Map;

public class ReportGenerator {

    public static void generateReport(Map<String, Object> reportData) {

        ObjectMapper mapper = new ObjectMapper();

        try {

            mapper.writerWithDefaultPrettyPrinter()
                    .writeValue(new File("report.json"), reportData);

            System.out.println("\nReport saved as report.json");
            FileWriter writer = new FileWriter("report.html");
            String html =
                "<html>\n" +
                "<head>\n" +
                "<title>DPI Traffic Analysis Report</title>\n" +

                "<style>\n" +

                "body{" +
                "font-family:Arial,sans-serif;" +
                "background:#f4f6f9;" +
                "margin:40px;" +
                "}\n" +

                ".container{" +
                "max-width:850px;" +
                "margin:auto;" +
                "background:white;" +
                "padding:30px;" +
                "border-radius:10px;" +
                "box-shadow:0 0 10px rgba(0,0,0,0.15);" +
                "}\n" +

                "h1{" +
                "text-align:center;" +
                "color:#1f4e79;" +
                "}\n" +

                "h2{" +
                "color:#1f4e79;" +
                "margin-top:35px;" +
                "}\n" +

                "table{" +
                "width:100%;" +
                "border-collapse:collapse;" +
                "margin-top:20px;" +
                "}\n" +

                "th{" +
                "background:#d9ecff;" +
                "}\n" +

                "th,td{" +
                "border:1px solid #ddd;" +
                "padding:12px 18px;" +
                "text-align:left;" +
                "}\n" +

                "</style>\n" +

                "</head>\n" +

                "<body>\n" +

                "<div class='container'>\n" +

                "<h1>DPI Traffic Analysis Report</h1>\n" +

                "<h2>General Statistics</h2>\n" +

                "<table>\n" +

                "<tr>" +
                "<th>Metric</th>" +
                "<th>Value</th>" +
                "</tr>" +

                "<tr>" +
                "<td>Total Packets</td>" +
                "<td>" + reportData.get("totalPackets") + "</td>" +
                "</tr>" +

                "<tr>" +
                "<td>Total Connections</td>" +
                "<td>" + reportData.get("totalConnections") + "</td>" +
                "</tr>" +

                "<tr>" +
                "<td>Total Bytes</td>" +
                "<td>" + reportData.get("totalBytes") + "</td>" +
                "</tr>" +

                "<tr>" +
                "<td>Average Bytes / Connection</td>" +
                "<td>" + reportData.get("averageBytesPerConnection") + "</td>" +
                "</tr>" +

                "<tr>" +
                "<td>Top Source IP</td>" +
                "<td>" + reportData.get("topSourceIP") + "</td>" +
                "</tr>" +

                "<tr>" +
                "<td>Top Destination IP</td>" +
                "<td>" + reportData.get("topDestinationIP") + "</td>" +
                "</tr>" +

                "<tr>" +
                "<td>Top Application</td>" +
                "<td>" + reportData.get("topApplication") + "</td>" +
                "</tr>" +

                "</table>\n" +

                "<hr>\n" +

                "<p style='text-align:center;color:gray;'>Generated by DPI Engine • Java • Pcap4J • Jackson</p>\n" +

                "</div>\n" +

                "</body>\n" +
                "</html>";
        writer.write(html);
        writer.close();

        System.out.println("Report saved as report.html");
        
        } catch (IOException e) {

            e.printStackTrace();

        }

    }
}